In [90]:
import tensorflow.compat.v1 as tf
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense


from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

tf.disable_v2_behavior()

In [83]:
df = pd.read_csv("Automobile_price_data_Raw_set.csv")
df_dropped = df.dropna(axis=0, how='any')

In [172]:
df_ind = df_dropped.loc[:, ['make', 'body-style', 'wheel-base', 'engine-size', 'horsepower', 'peak-rpm', 'highway-mpg']]
df_dep = df_dropped.loc[:,'price']



# Transferred manually Audi to 0 and hatchback to 2 which
# correlated categories with training data.
prediction = [ 0, 2, 99.5, 131, 160, 5500, 22 ]

df_pred = pd.DataFrame(prediction)

df_ind.append(df_pred)
df_ind.tail()

,make,body-style,wheel-base,engine-size,horsepower,peak-rpm,highway-mpg
200,volvo,sedan,109.1,141,114.0,5400.0,28
201,volvo,sedan,109.1,141,160.0,5300.0,25
202,volvo,sedan,109.1,173,134.0,5500.0,23
203,volvo,sedan,109.1,145,106.0,4800.0,27
204,volvo,sedan,109.1,141,114.0,5400.0,25

In [173]:

# Label encoding
labelencoder_make = LabelEncoder()
df_ind.loc[:,'make'] = labelencoder_make.fit_transform(df_ind.loc[:,'make'])



labelencoder_bodystyle = LabelEncoder()
df_ind.loc[:,'body-style'] = labelencoder_bodystyle.fit_transform(df_ind.loc[:,'body-style'])
df_ind.head()

,make,body-style,wheel-base,engine-size,horsepower,peak-rpm,highway-mpg
3,0,3,99.8,109,102.0,5500.0,30
4,0,3,99.4,136,115.0,5500.0,22
6,0,3,105.8,136,110.0,5500.0,25
8,0,3,105.8,131,140.0,5500.0,20
10,1,3,101.2,108,101.0,5800.0,29

In [179]:
X_train, X_test, Y_train, Y_test = train_test_split( df_ind , df_dep , test_size = 0.2, random_state = 0)

sc_X = StandardScaler()
#print("original")
#print(df_ind)
#print("train")
#print(X_train)
#print("test")
#print(X_test)
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.fit_transform(X_test)

df_pred = sc_X.fit_transform(df_pred)



#type(X_train)
#type(Y_train)   
sc_Y = StandardScaler()
Y_train = sc_Y.fit_transform(Y_train.values.reshape(-1,1))
Y_test = sc_Y.fit_transform(Y_test.values.reshape(-1,1))

[[-0.44438441]
 [-0.44333252]
 [-0.39205307]
 [-0.37548586]
 [-0.3602335 ]
 [ 2.44830302]
 [-0.43281366]]

In [184]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim = 7)) 
model.add(Dense(units=100, activation='relu')) 
model.add(Dense(units=100, activation='relu')) 
model.add(Dense(units=100, activation='relu')) 

model.add(Dense(units=1))

model.compile(loss='mean_squared_error', optimizer='adam', metrics = ['accuracy'])

model.fit(X_train, Y_train, epochs=1000, verbose=0)

# evaluate the model
mse_value, acc = model.evaluate(X_test, Y_test, verbose=0)
print('Evaluation MSE: '+str(mse_value))
print('Evaluation accuracy: '+str(acc))
# predict the value
Y_pred = model.predict(df_pred.reshape(1, -1))
print(sc_Y.inverse_transform(Y_pred))

Evaluation MSE: 0.1893409639596939
Evaluation accuracy: 0.0
[[8396.433]]